### ISSUE TITLE
Add Title for default cropVariant

### ISSUE THREAD

**Issue by FaraFara** [josefglatz/cropvariantsbuilder#11]
How to set 'title' for cropVariant? 
```
     defaultCropVariantsConfiguration:
        default:
          title: "Default Max"
          aspectRatios:
            - "3:2"
            - "2:3"
```
This example don't work

Same this:
```
'cropVariants' => [
                            'default' => [
                                'title' => 'Default Max',

```
