### ISSUE TITLE
[DOC] clarify how to override default-values

### ISSUE THREAD

**Issue by infabo** [josefglatz/cropvariantsbuilder#14]
Override default configuration as described in the documentation does not work out.

https://github.com/josefglatz/cropvariantsbuilder#example-of-using-your-own-cropvariantsyaml-file-while-using-the-typo3cmscoreconfigurationloaderyamlfileloader-load-imports-feature

YamlFileLoader processes imports using `ArrayUtility::replaceAndAppendScalarValuesRecursive`. That "excellent" utility function rather appends than merging arrays. Neither append nor merging is right. It would need a replace.

So referring to the doc example:

## ext:cropvariants default config

```yaml
      defaultCropVariantsConfiguration:
        default:
          aspectRatios:
            - "3:2"
            - "2:3"
            - "4:3"
            - "3:4"
            - "1:1"
            - "NaN"
```

doc sample: 

```yaml
imageManipulation:
  cropVariants:
    defaults:
      aspectRatios:
        "1.91:1":
          title: "This is the new title for an existing aspectRatio within EXT:cropvariantsbuilder"
        "123:321":
          title: "Completely new introduced aspect ratio"
          value: 123 / 321

      defaultCropVariantsConfiguration:
        default:
          aspectRatios:
            - "3:2"
            - "2:3"
            - "123:321"
            - "NaN"

imports:
  -
    resource: 'EXT:cropvariantsbuilder/Configuration/ImageManipulation/CropVariants.yaml'
```

It is not possible to reduce `defaultCropVariantsConfiguration/default/aspectRatios` to these 4 values.

Actually it ends up into something like this:

```yaml
      defaultCropVariantsConfiguration:
        default:
          aspectRatios:
            - "3:2"
            - "2:3"
            - "4:3"
            - "3:4"
            - "1:1"
            - "NaN"
            - "3:2"
            - "2:3"
            - "123:321"
            - "NaN"
```
